# Alternative Netlify configuration - minimal approach
[build]
  command = "cd frontend && npm ci && npx ng build --configuration=netlify && if [ -d 'dist/scouteando/browser' ]; then mv dist/scouteando/browser/* dist/scouteando/ && rm -rf dist/scouteando/browser; fi"
  publish = "frontend/dist/scouteando"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/assets/content/*"
  [headers.values]
    Cache-Control = "public, max-age=300"

[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000"
