[build]
  command = "cd frontend && npm install && npm run build -- --configuration=netlify && if [ -d 'dist/scouteando/browser' ]; then mv dist/scouteando/browser/* dist/scouteando/ && rm -rf dist/scouteando/browser; fi"
  publish = "frontend/dist/scouteando"

# Configuración de Node.js
[build.environment]
  NODE_VERSION = "18"

# Deshabilitar procesamiento automático que puede interferir
[build.processing]
  skip_processing = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/assets/content/*"
  [headers.values]
    Cache-Control = "public, max-age=300"

[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000"
