name: Deploy Angular to GitHub Pages
on:
  push:
    branches:
      - main  # Asegúrate de que el nombre de la rama coincida (main/master)

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4  # Versión actualizada

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: Install Dependencies
        run: npm install

      - name: Build Angular App
        run: npm run build -- --base-href="/scouteando/"

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          folder: dist/scouteando  # Revisa en angular.json la ruta exacta
          clean: true