name: Build and Deploy
on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x  # Angular 17+ es compatible con Node 20

      - name: Install Dependencies
        run: npm install

      - name: Build Angular App
        run: npm run build -- --base-href="/scouteando/"  # Base href para GitHub Pages

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          folder: dist/scouteando  # Asegúrate de que coincida con tu angular.json
          clean: true  # Borra archivos antiguos en gh-pages