name: Deploy Angular
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: Replace API Key
        run: |
          sed -i "s|DRIVE_API_KEY|${{ secrets.DRIVE_API_KEY }}|g" src/environments/environment.prod.ts

      - name: Install and Build
        run: |
          npm install
          npm run build -- --configuration=production --base-href="/scouteando/"

      - name: Deploy to GH Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          folder: dist/scouteando