name: Deploy Angular to GitHub Pages
on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: Install Frontend Dependencies
        run: |
          cd frontend
          npm install

      - name: Build Angular App
        run: |
          cd frontend
          
          # Elimina builds anteriores para evitar conflictos
          rm -rf dist/scouteando
          
          # Construye la app (los archivos se generarán en dist/scouteando/browser)
          npm run build -- --configuration=production --base-href="/scouteando/" --deploy-url="/scouteando/"

          # Mueve los archivos de /browser a la raíz de dist/scouteando
          mv dist/scouteando/browser/* dist/scouteando/
          
          # Elimina la carpeta browser (ya vacía)
          rm -rf dist/scouteando/browser
          
          # Crea .nojekyll para desactivar Jekyll
          touch dist/scouteando/.nojekyll

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: frontend/dist/scouteando